import java.lang.reflect.Method;
public class O {
     public static void main(String[]args)throws IllegalAccessException{
        Class klass=Teacher.class;
       
        Method[] arr=klass.getMethods();
       
        for(Method next:arr){
        System.out.println(next.getName()+  ".....");
       
        }
            
        }
    }
// T2.....
// p2.....
// equals.....
// toString.....
// hashCode.....
// getClass.....
// notify.....
// notifyAll.....
// wait.....
// wait.....
// wait.....